// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLziqsC3pOAgHJLzn363-nhW2teJ24j8k',
    appId: '1:520246753991:web:93762d0e71743a7d911ce2',
    messagingSenderId: '520246753991',
    projectId: 'baatcheet-kare',
    authDomain: 'baatcheet-kare.firebaseapp.com',
    storageBucket: 'baatcheet-kare.appspot.com',
    measurementId: 'G-WVH0QJYX5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBz10sguKBiHVlRCCmAv1XRfjrZUJLdKQ',
    appId: '1:520246753991:android:28d6299a5cc9a23f911ce2',
    messagingSenderId: '520246753991',
    projectId: 'baatcheet-kare',
    storageBucket: 'baatcheet-kare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSjV3xkKawzCw9fDS9f9-jxB7hcZQmFtQ',
    appId: '1:520246753991:ios:7b1fab31574f802c911ce2',
    messagingSenderId: '520246753991',
    projectId: 'baatcheet-kare',
    storageBucket: 'baatcheet-kare.appspot.com',
    iosBundleId: 'com.example.baatCheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSjV3xkKawzCw9fDS9f9-jxB7hcZQmFtQ',
    appId: '1:520246753991:ios:7b1fab31574f802c911ce2',
    messagingSenderId: '520246753991',
    projectId: 'baatcheet-kare',
    storageBucket: 'baatcheet-kare.appspot.com',
    iosBundleId: 'com.example.baatCheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLziqsC3pOAgHJLzn363-nhW2teJ24j8k',
    appId: '1:520246753991:web:395fe7fd24de4dac911ce2',
    messagingSenderId: '520246753991',
    projectId: 'baatcheet-kare',
    authDomain: 'baatcheet-kare.firebaseapp.com',
    storageBucket: 'baatcheet-kare.appspot.com',
    measurementId: 'G-ZZQKX1H8HH',
  );
}
